Style changes

diff --git a/addkey b/addkey
--- a/addkey
+++ b/addkey
@@ -1,32 +1,24 @@
 #!/bin/sh
 
-# Read in the SSH key
-echo "Input the key to be added:"
+echo "Paste the key to be added:"
 read key
 
-# Place the key in a temporary file (it's hard to get ssh-keygen
-# to read from stdin; <<< works for bash, but is non-posix)
-keyfile=$(tempfile) && echo "$key" > $keyfile
+keyfile="$(mktemp)"
+echo "$key" > "$keyfile"
 
-# Generate a fingerprint
-fingerprint=$(ssh-keygen -lf $keyfile)
-
-# Check for errors
-if [ $(echo "$fingerprint" | egrep -c '(R|D)SA') -eq 0 ]
-then
-  # Display the fingerprint error and clean up
-  echo "Error: $fingerprint"
-  rm $keyfile
-  exit 1
+# check for errors
+fingerprint="$(ssh-keygen -lf $keyfile)"
+if [ "$(echo "$fingerprint" | egrep -c '\((R|D)SA|ED25519\)')" -ne "1" ]; then
+    echo "Error: $fingerprint"
+    rm "$keyfile"
+    exit 1
 fi
 
-# Add the key to the authorised keys file and clean up
 mkdir -p .ssh && \
   echo -n "no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty " >> .ssh/authorized_keys && \
-  cat $keyfile >> .ssh/authorized_keys
+  cat "$keyfile" >> .ssh/authorized_keys
 
-rm $keyfile
+rm "$keyfile"
 
-# Display the fingerprint for reference
 echo "Success! Added a key with the following fingerprint:"
-echo $fingerprint
+echo "$fingerprint"
